### ISSUE TITLE
How to use it? C++ and/or C#?

### ISSUE THREAD

**Issue by Vildnex** [Logerfo/sln-support#1]
Hey,

I think this is finally what I was searched for in the past few weak, great work. 

I do have just 2 questions:

1. How can I actually use it? I've downloaded the extension of VSCode but how can I open a .sln project after that? Could you provide some information, instructions, like, anything? 

2. It's working with any Visual Studio project(C# and C++)? Or just with one of them?

Thanks for your effort and time :)

**Comment by Logerfo** [comment]
@Vildnex based on your questions, I think that, unfortunately, you did not find what you were looking for. The only thing my extension can do at the moment is syntax highlight `.sln` files. You cannot open solutions like you would in Visual Studio (IDE). I think this might be a good idea, though. Perhaps I could think of a _solution_ (pun intended) in the future.

**Comment by Logerfo** [comment]
Check [this](https://github.com/fernandoescolar/vscode-solution-explorer) out, it might help you.
