### ISSUE TITLE
No explanation on how it works and nothing happens.

### ISSUE THREAD

**Issue by NicTanghe** [Logerfo/sln-support#2]
i open a folder with a .sln file and nothing happens.
its a c++ sln file.

**Comment by Logerfo** [comment]
I think the feature your looking for is provided by [this](https://marketplace.visualstudio.com/items?itemName=fernandoescolar.vscode-solution-explorer) extension (vscode-solution-explorer).
The only thing my extension (sln-support) does is to provide syntax highlight to the sln file.

**Comment by NicTanghe** [comment]
thx it also doens't do what i want because no c++ support there still thx 4
the quick reply.

(plz ad syntax highlighting to the description tho)

Op do 27 feb. 2020 om 16:39 schreef Bruno Logerfo <notifications@github.com
